### ISSUE TITLE
Translate to English ALLqueries.sql in clear_after_conflict commit

### ISSUE THREAD

**Issue by AnnaKnig** [nromanen/Ch-QC#1]

**Comment by AnnaKnig** [comment]
translate to English one part

**Comment by HalynaMur** [comment]
In my part all in English

**Comment by Mikysik** [comment]
Translate to English my part

**Comment by gandabura** [comment]
In my part only English

**Comment by Nikolas9896** [comment]
Please provide the link or simple text or screen.... which isn't in English...
